name: Build
on:
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
    
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B install -DskipTests -Pcheckstyle,findbugs

  build:
    needs: checkstyle
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version:  17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn verify

      - name: Upload Test Results
        if:  ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: '**/*-reports/TEST-*.xml'

  event_file:
    name: Upload event file
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Event File
        path: ${{ github.event_path }}
