name: build
on:
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
    
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B install -DskipTests -Pcheckstyle,findbugs

  build:
    needs: checkstyle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        module: [ 'hazelcast-hibernate53' ]
    name: Build ${{ matrix.module }} with JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -f ${{ matrix.module }}/pom.xml verify


