name: Build snapshot
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        hazelcast: [ '5.1-SNAPSHOT' ]
    name: Build against Hazelcast ${{ matrix.hazelcast }} with JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -Dhazelcast.version=${{ matrix.hazelcast }} verify

