name: Compatiblity Builds
on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - master
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event_name != 'labeled' || github.event.label.name == 'compatibility-sensitive' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hazelcast: [ '4.1.9', '4.2.5', '5.0.3', '5.1.3', '5.2-SNAPSHOT' ]
        hibernate: [ '5.3.28.Final', '5.4.33.Final', '5.5.9.Final', '5.6.11.Final', '6.0.2.Final', '6.1.3.Final' ]
    name: Build with HZ ${{ matrix.hazelcast }} and HN ${{ matrix.hibernate }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -Dhazelcast.version=${{ matrix.hazelcast }} -Dhibernate.core.version=${{ matrix.hibernate }} verify

  test-jdks:
    if: ${{ github.event_name != 'labeled' || github.event.label.name == 'compatibility-sensitive' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Build with JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn verify

