name: Release Snapshot

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ 'hazelcast-hibernate53' ]
    name: Release ${{ matrix.module }} snapshot
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version:  17
          distribution: 'temurin'
          cache: 'maven'
          server-id: snapshot-repository
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Deploy ${{ matrix.module }} snapshot
        run: mvn deploy -Prelease-snapshot --batch-mode --update-snapshots -DskipTests -DretryFailedDeploymentCount=3
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_OSS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_OSS_PASSWORD }}
